targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      retrofit_generator:
        enabled: true
      riverpod_generator:
        options:
          riverpod_generator:
            scoped_providers_names:
              - apiClient
              - dio
